### ISSUE TITLE
Redirect from HTTP to HTTPS to HTTPSS [commit efd3c92]

### ISSUE THREAD

**Issue by jackwherry** [ThunderDynamics/tdic#1]
This commit (efd3c92)  breaks this site on my computer. The following message shows up on Chromium 58 on Linux: 

![thunder_error](https://cloud.githubusercontent.com/assets/17338790/25772061/beacbf6a-3227-11e7-84f3-f115b6f3c529.png)

At this point, if I choose to open the "file" in `xdg-open`, then it opens in the default catch-all internet file opener and gives an error because no app on my computer can open "HTTPSS:" files. Even if I manually change HTTPS to HTTP, the error continues. The page seems to redirect to HTTPS and then to HTPSS, which is the problem. 

The regex string continues to redirect even if the URL already contains HTTPS, adding more and more S at the end. 

EDIT 0: Will attach more screenshots from other browsers.

EDIT 1: The following screenshots were generated with BrowserStack:

![nexus-9](https://www.browserstack.com/screenshots/554ecf617b7382753bb9c1b72ff1280ba6eea631/android_Google-Nexus-9_5.0_portrait.png)

Google Nexus 9 on Android 5

![ie-11-win-10](https://www.browserstack.com/screenshots/554ecf617b7382753bb9c1b72ff1280ba6eea631/win10_ie_11.0.png)

Internet Explorer 11 on Windows 10

Firefox 44 on Windows 10 does not show you an error message, it just gives a help page with information about how to set your default browser: 

![ff-44-win-10](https://www.browserstack.com/screenshots/554ecf617b7382753bb9c1b72ff1280ba6eea631/win10_firefox_44.0.jpg)

Firefox 44 on Windows 10

More screenshots to come....

**Comment by eado** [comment]
Fixed it.

**Comment by jackwherry** [comment]
Good, thanks.
